// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcJTWXtu0W35LsnZTTzqgCynjmZLE2iIU',
    appId: '1:345943993270:web:9cffbbef1b06edbe446f17',
    messagingSenderId: '345943993270',
    projectId: 'news-aggregator-a4193',
    authDomain: 'news-aggregator-a4193.firebaseapp.com',
    storageBucket: 'news-aggregator-a4193.firebasestorage.app',
    measurementId: 'G-QY17KTC0L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqSbcSaHU98Qph6rQF_q7_idESF9A3cHY',
    appId: '1:345943993270:android:868050451b7e8818446f17',
    messagingSenderId: '345943993270',
    projectId: 'news-aggregator-a4193',
    storageBucket: 'news-aggregator-a4193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9IcDix8pAO2G0RZzQjnFUWA6s_RZ52yY',
    appId: '1:345943993270:ios:7ce8fb668ef8d5b4446f17',
    messagingSenderId: '345943993270',
    projectId: 'news-aggregator-a4193',
    storageBucket: 'news-aggregator-a4193.firebasestorage.app',
    androidClientId: '345943993270-frari5bttikqpppk9jja76fd18jeflak.apps.googleusercontent.com',
    iosClientId: '345943993270-hflhito1fk4q4clamjjt2dleunl3h1sq.apps.googleusercontent.com',
    iosBundleId: 'com.ooad.newsaggregator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9IcDix8pAO2G0RZzQjnFUWA6s_RZ52yY',
    appId: '1:345943993270:ios:7ce8fb668ef8d5b4446f17',
    messagingSenderId: '345943993270',
    projectId: 'news-aggregator-a4193',
    storageBucket: 'news-aggregator-a4193.firebasestorage.app',
    androidClientId: '345943993270-frari5bttikqpppk9jja76fd18jeflak.apps.googleusercontent.com',
    iosClientId: '345943993270-hflhito1fk4q4clamjjt2dleunl3h1sq.apps.googleusercontent.com',
    iosBundleId: 'com.ooad.newsaggregator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcJTWXtu0W35LsnZTTzqgCynjmZLE2iIU',
    appId: '1:345943993270:web:f13e2ccdd1989f01446f17',
    messagingSenderId: '345943993270',
    projectId: 'news-aggregator-a4193',
    authDomain: 'news-aggregator-a4193.firebaseapp.com',
    storageBucket: 'news-aggregator-a4193.firebasestorage.app',
    measurementId: 'G-6HSJ7ETVKC',
  );
}
