name: Deploy to Firebase Hosting, APK, and IPA on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Java version (Java 11, for example)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2

      # Build Flutter web
      - name: Build Flutter web
        run: flutter build web

      # Build Flutter APK
      - name: Build Flutter APK
        run: flutter build apk --release

      # Deploy Flutter web to Firebase Hosting
      - name: Deploying Web to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEWS_AGGREGATOR_A4193 }}
          channelId: live
          projectId: news-aggregator-a4193

      # Install Firebase CLI to deploy APK
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      # Deploy APK to Firebase App Distribution
      - name: Deploying APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app "1:345943993270:android:868050451b7e8818446f17" \
          --token ${{ secrets.FIREBASE_TOKEN }}

  build_ios:
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2

      # Run flutter pub get to generate dependencies
      - name: Run flutter pub get
        run: flutter pub get

      # Set up CocoaPods
      - name: Install CocoaPods
        run: pod install --project-directory=ios

      # Build Flutter iOS
      - name: Build Flutter iOS
        run: flutter build ipa --release

      # Deploy IPA to Firebase App Distribution
      - name: Deploying IPA to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/ios/ipa/release.ipa \
          --app "1:345943993270:ios:123456abcdef" \
          --token ${{ secrets.FIREBASE_TOKEN }}
